### PR TITLE
Added some HTML/CSS design

### PR DESCRIPTION
**Pull request by erikasland**
Added some html/css design to the basic structure. 

- Added background image 
- Centered buttons
- Resized everything
- Linked index to responsive.css page to start making media queries that can in turn make the page responsive

### CODE REVIEW

**Comment by em77** [comment]
This looks great but I noticed when clicking on buttons the background image resizes up and down. Is it possible to fix that? Also, can the whole thing be made maybe 20-30% smaller? That way it fits better on smaller screens without having to scroll down to see the New Game button.

**Comment by erikasland** [comment]
Huh. I am not getting that on either of my computers. Are you using Safari? I am sure I can fix it if I understand why that is happening for you. Also, my next step was to make the page responsive with media queries, which would change the layout of the page as it gets smaller so the design can stay how it is now and adapt as the page shrinks. If you haven't heard of media queries, look them up. They are essential in making responsive web pages. My about me web page was made responsive using media queries if you would like to check that out.

**Comment by erikasland** [comment]
http://erikasland.github.io/

Go to this and resize the window. Tell me what you think.

**Comment by em77** [comment]
I tried on Firefox, Chrome, and Safari. On Safari the dice are all the way at the bottom of the box and enlarged also. Ugh, these different browsers. But yeah all three were doing this thing where the background imagine resized a bit almost every time you hit Roll. Maybe in the next changes it'll change that. It overall looks good though!

**Pull request merged**
